### ISSUE TITLE
fix course date

### ISSUE THREAD

**Issue by paschatz** [paschatz/WorOptReproSciEcoEnvSci#1]
The approval of the lecture date is still pending. Once it is confirmed, this repository will be updated accordingly.

**Comment by kostheo71** [comment]
> The approval of the lecture date is still pending. Once it is confirmed, this repository will be updated accordingly.

Thursday 26/10, 12.00-15.00 in the computer lab. 
I think we can use Github but I'll confirm with Antonis Andreou.

**Comment by paschatz** [comment]
Perfect,

I will arrange my flight :)
